const val composeVersion = "1.5.1"
const val composeWasmVersion = "1.4.0-dev-wasm08"
const val composeCompilerVersion = "1.5.1"
const val kotlinVersion = "1.9.10"
const val androidGradlePluginVersion = "8.0.0"
const val androidComposeBomVersion = "2023.09.00"
const val androidComposeCompilerVersion = "1.5.3"